export const PERMISSION = Object.freeze(
  {
    EDX_USER_SCHOOL_ADMIN: 'EDX_USER_SCHOOL_ADMIN',

    SECURE_EXCHANGE: 'SECURE_EXCHANGE',

    EDX_USER_DISTRICT_ADMIN: 'EDX_USER_DISTRICT_ADMIN',

    STUDENT_DATA_COLLECTION: 'STUDENT_DATA_COLLECTION'
  }
);

