export const PERMISSION = Object.freeze(
  {
    EDX_USER_SCHOOL_ADMIN: 'EDX_USER_SCHOOL_ADMIN',

    SECURE_EXCHANGE: 'SECURE_EXCHANGE',

    EDX_USER_DISTRICT_ADMIN: 'EDX_USER_DISTRICT_ADMIN',

    SCHOOL_SDC: 'SCHOOL_SDC',

    EDX_SCHOOL_EDIT: 'EDX_SCHOOL_EDIT',

    EDX_DISTRICT_EDIT: 'EDX_DISTRICT_EDIT',

    EDX_USER_SCHOOL_ADMIN: 'SCHOOL_SDC',
  }
);

