export const PERMISSION = Object.freeze(
  {
    EDX_USER_SCHOOL_ADMIN: 'EDX_USER_SCHOOL_ADMIN',

    SECURE_EXCHANGE: 'SECURE_EXCHANGE',

    EDX_USER_DISTRICT_ADMIN: 'EDX_USER_DISTRICT_ADMIN',

    DISTRICT_SDC_VIEW: 'DIS_SDC_VIEW',

    SCHOOL_SDC_VIEW: 'SCH_SDC_VIEW',

    SCHOOL_SDC_EDIT: 'SCH_SDC_EDIT',

    DISTRICT_SDC_EDIT: 'DIS_SDC_EDIT',

    EDX_SCHOOL_VIEW: 'EDX_SCHOOL_VIEW',

    EDX_SCHOOL_EDIT: 'EDX_SCHOOL_EDIT',

    EDX_DISTRICT_VIEW: 'EDX_DISTRICT_VIEW',

    EDX_DISTRICT_EDIT: 'EDX_DISTRICT_EDIT',

    GRAD_SCH_EDIT: 'GRAD_SCH_EDIT',

    EAS_DIS_EDIT: 'EAS_DIS_EDIT',

    EAS_SCH_EDIT: 'EAS_SCH_EDIT',

  }
);

