export const ROLES = Object.freeze(
  {
    EDX_EDIT_SCHOOL: 'EDX_EDIT_SCHOOL',
    EDX_EDIT_DISTRICT: 'EDX_EDIT_DISTRICT',
    EDX_DISTRICT_ADMIN: 'EDX_DISTRICT_ADMIN',
    EDX_SCHOOL_ADMIN: 'EDX_SCHOOL_ADMIN',
    SECURE_EXCHANGE_SCHOOL: 'SECURE_EXCHANGE_SCHOOL',
    SECURE_EXCHANGE_DISTRICT: 'SECURE_EXCHANGE_DISTRICT',
    SUPERINT: 'SUPERINT',
    SECR_TRES: 'SECR_TRES',
    DIS_SDC_RO: 'DIS_SDC_RO',
    SCH_SDC_RO: 'SCH_SDC_RO',
    SCHOOL_SDC: 'SCHOOL_SDC',
    DISTRICT_SDC: 'DISTRICT_SDC'
  }
);

