const PERMISSION = Object.freeze(
  {
    DISTRICT_SDC: 'DISTRICT_SDC',
    EDX_SCHOOL_EDIT: 'EDX_SCHOOL_EDIT',
    EDX_DISTRICT_EDIT: 'EDX_DISTRICT_EDIT',
    EDX_USER_SCHOOL_ADMIN: 'EDX_USER_SCHOOL_ADMIN',
    EDX_USER_DISTRICT_ADMIN: 'EDX_USER_DISTRICT_ADMIN',
    SECURE_EXCHANGE: 'SECURE_EXCHANGE',
    SCHOOL_SDC: 'SCHOOL_SDC'
  }
);

module.exports = {
  PERMISSION,
};
