const PERMISSION = Object.freeze(
  {
    EDX_SCHOOL_VIEW: 'EDX_SCHOOL_VIEW',
    EDX_SCHOOL_EDIT: 'EDX_SCHOOL_EDIT',
    EDX_DISTRICT_VIEW: 'EDX_DISTRICT_VIEW',
    EDX_DISTRICT_EDIT: 'EDX_DISTRICT_EDIT',
    EDX_USER_SCHOOL_ADMIN: 'EDX_USER_SCHOOL_ADMIN',
    EDX_USER_DISTRICT_ADMIN: 'EDX_USER_DISTRICT_ADMIN',
    SECURE_EXCHANGE: 'SECURE_EXCHANGE',
    DISTRICT_SDC_EDIT: 'DIS_SDC_EDIT',
    SCHOOL_SDC_EDIT: 'SCH_SDC_EDIT',
    DISTRICT_SDC_VIEW: 'DIS_SDC_VIEW',
    SCHOOL_SDC_VIEW: 'SCH_SDC_VIEW'
  }
);

const ROLE = Object.freeze(
  {
    EDX_EDIT_SCHOOL: 'EDX_EDIT_SCHOOL',
    EDX_EDIT_DISTRICT: 'EDX_EDIT_DISTRICT',
    EDX_DISTRICT_ADMIN: 'EDX_DISTRICT_ADMIN',
    EDX_SCHOOL_ADMIN: 'EDX_SCHOOL_ADMIN',
    SECURE_EXCHANGE_SCHOOL: 'SECURE_EXCHANGE_SCHOOL',
    SECURE_EXCHANGE_DISTRICT: 'SECURE_EXCHANGE_DISTRICT',
    SUPERINT: 'SUPERINT',
    SECR_TRES: 'SECR_TRES',
    DIS_SDC_RO: 'DIS_SDC_RO',
    SCH_SDC_RO: 'SCH_SDC_RO',
    SCHOOL_SDC: 'SCHOOL_SDC',
    DISTRICT_SDC: 'DISTRICT_SDC'
  }
);

module.exports = {
  PERMISSION,
  ROLE
};
