export default {
  accessUsersPage: {
    manageSchoolButton: '#manageSchoolButton',
    schoolSelectorBox: 'div[role="listbox"]',
    selectSchoolDropdown: '#selectInstituteName',
    accessUserFeedback: '.v-alert__content',
    confirmationDialog: '.v-overlay__content'
  },
  careerProgramComponent: {
    tab: '#careerTab',
    filterButton: '#filters',
    summaryButton: '#careerSummaryButton',
    headcountCard: '.career-headcount-card',
    headcountHeader: '.career-headcount-header',
    headcountColumnData: '.career-headcount-column-data'
  },
  dashboard: {
    dataCollectionsTile: '#studentDataCollectionCard',
    dataCollectionsTileTitle: '#studentDataCollectionCard > div.v-row.pl-4 > div.v-col.mt-2 > div:nth-child(1) > div > h4',
    districtContactsCard: '#districtContactsCard',
    districtDetailsCard: '#districtDetailsCard',
    districtUserSchoolContactsCard: '#districtUserSchoolContactsCard',
    schoolContactsCard: '#schoolContactsCard',
    schoolDetailsCard: '#schoolDetailsCard',
    secureMessageTile: '#secureMessageInboxCard',
    title: '#navTitle'
  },
  dataCollectionsLanding: {
    continue: '.navigate',
    title: '#navTitle > div'
  },
  datePicker: {
    nextArrow: 'div.dp__month_year_row > button:nth-child(3)',
    day: '.dp__calendar_row:nth-child(2) > .dp__calendar_item:nth-child(1)'
  },
  districtContacts: {
    deleteCancelButton: '#rejectBtn',
    deleteConfirmButton: '#resolveBtn',
    deleteContactButton: '#removeContactButton',
    editContactFirstNameInput: '#editContactFirstNameInput',
    editContactLastNameInput: '#editContactLastNameInput',
    editDistrictContactButton: '#editContactButton',
    filterContactClearButton: '#district-clear-button',
    listItem: '.v-list-item',
    newContactButton: '#newContactButton',
    newContactEffectiveDateTextField: '#newContactEffectiveDateTextField',
    newContactEmailInput: '#newContactEmailInput',
    newContactFirstNameInput: '#newContactFirstNameInput',
    newContactLastNameInput: '#newContactLastNameInput',
    newContactPhoneNumberInput: '#newContactPhoneNumberInput',
    newContactPostBtn: '#newContactPostBtn',
    newContactTypeDropdown: '#newContactDropdown',
    saveChangesToDistrictContactButton: '#saveChangesToDistrictContactButton',
    searchContactButton: '#district-search-button',
    searchContactFirstNameInput: '#first-name-search-text-field',
    searchContactLastNameInput: '#last-name-search-text-field',
    searchContactTypeDropdown: '#status-select-field',
    subjectHeading: 'h2.subjectHeading',

  },
  districtDetails: {
    addWebsiteLink: 'a.editField',
    districtDetailsWebsite: '#districtDetailsWebsite',
    editAddressMailCity: '#mailAddressCity',
    editAddressPostalCode: '#mailAddressPostal',
    editDistrictDetailsButton: '#districtDetailsEditButton',
    editDistrictEmail: '#districtDetailsEmail',
    editDistrictPhone: '#districtDetailsPhoneNumber',
    editDistrictFax: '#districtDetailsFaxNumber',
    editMailingAddressCountry: '#mailAddressCountry',
    editMailingAddressLine1: '#mailAddressLine1',
    editMailingAddressProvince: '#mailAddressProvince',
    editPopupConfirmButton: '#resolveBtn',
    editPopupReturnButton: '#rejectBtn',
    editSaveButton: '#saveButton',
  },
  documentUpload: { //common component
    selectFileInput: '#selectFileInput',
    uploadDocumentButton: '#upload_form',
    uploadDocumentTypeCodeSelect: '#uploadDocumentTypeCodeSelect',
    stepThreeNextButton: '#nextButton',
  },
  dropdown: { //common component
    listItem: '.v-list-item'
  },
  frenchComponent: {
    tab: '#frenchTab',
    filterButton: '#filters',
    summaryButton: '#frenchSummaryButton',
    headcountCard: '.french-headcount-card',
    headcountHeader: '.french-headcount-header',
    headcountColumnData: '.french-headcount-column-data'
  },
  fteComponent: {
    tab: '#enrollmentTab',
    filterButton: '#filters',
    summaryButton: '#fteSummaryButton',
    headcountCard: '.enrollment-headcount-card',
    headcountHeader: '.enrollment-headcount-header',
    headcountColumnData: '.enrollment-headcount-column-data'
  },
  hamburgerMenu: {
    administrationMenuOption: '#AdministrationMenuBtn',
    districtUserManagementOption: '#DistrictUserManagementMenuBtn',
    edxAccessMenuLink: '#UserManagementMenuBtn',
    hamburgerMenuButton: '#menuBtn',
    schoolUserManagementOption: '#SchoolUserManagementMenuBtn',
    secureMessagingInboxMenuButton: '#SecureMessagingInboxMenuBtn'
  },
  indigenousSupportComponent: {
    tab: '#indProgTab',
    filterButton: '#filters',
    summaryButton: '#indProgSummaryButton',
    headcountCard: '.indigenous-headcount-card',
    headcountHeader: '.indigenous-headcount-header',
    headcountColumnData: '.indigenous-headcount-column-data'
  },
  filters: {
    clearFilter: '#clear-filter',
    applyFilter: '#apply-filter',
    studentType: '#studentType',
    warnings: '#warnings',
    fte: '#fte',
    fundingtype: '#fundingtype',
    grade: '#grade',
    isSchoolAged: '#isSchoolAged',
    isAdult: '#isAdult',
    fteEq0: '#fteEq0',
    fteGt0: '#fteGt0',
  },
  invitationSelection: {
    loginButtonBCeID: '#login-button-bceid',
    loginButtonMicrosoft: '#login-button-microsoft',
  },
  loginPage: {
    loginUsername: '#user',
    loginPassword: '#password',
    loginContinueButton: 'input[name="btnSubmit"][value="Continue"]',
  },
  logoutPage: {
    logoutText: '#logout_text'
  },
  newUserInvites: {
    emailInput: '#newUserEmail',
    firstNameInput: '#newUserFirstName',
    generateNewCode: '#doGeneratePrimaryEdxActivationCodeButton',
    lastNameInput: '#newUserLastName',
    newUserButton: '#new-user-button',
    newUserInviteVCard: '#newUserInviteVCard',
    primaryActivationCode: '#primaryEdxActivationCode',
    rolesSelectorBox: '#instituteNewUserRolesListBox',
    rolesSelectorDropdown: '#instituteNewUserRolesSelect',
    sendInviteButton: '#newUserInvitePostBtn',
    toggleGenerateNewCode: '#toggleGenerateNewPrimaryEdxActivationCodeDialogVisibilityButton',
    noActivationCodeBanner: '#no-activation-code-banner'
  },
  schoolContacts: {
    cancelContactButton: '#cancelContactBtn',
    deleteCancelButton: '#rejectBtn',
    deleteConfirmButton: '#resolveBtn',
    deleteContactButton: '#removeContactButton',
    editContactButton: '#editContactButton',
    editContactEmailInput: '#editContactEmailInput',
    editContactFirstNameInput: '#editContactFirstNameInput',
    editContactLastNameInput: '#editContactLastNameInput',
    editContactPhoneNumberInput: '#editContactPhoneNumberInput',
    editContactSaveButton: '#editContactPostBtn',
    listItem: '.v-list-item',
    newContactButton: '#addSchoolContactBtn',
    newContactEffectiveDateTextField: '#newContactEffectiveDatePicker',
    newContactEmailInput: '#newContactEmailInput',
    newContactFirstNameInput: '#newContactFirstNameInput',
    newContactLastNameInput: '#newContactLastNameInput',
    newContactPhoneNumberInput: '#newContactPhoneNumberInput',
    newContactPostBtn: '#newContactPostBtn',
    newContactTypeDropdown: '#newContactDropdown',
    subjectHeading: 'h2.subjectHeading',
    resolveButton:'#resolveBtn',
    activeTab: '#schoolContactsTab',
  },
  schoolDetails: {
    addAddressButton: '#addAddressButton',
    addWebsiteLink: 'a.editField',
    editableFieldAlert: '.v-alert__content',
    editAddressMailCity: '#mailAddressCity',
    editAddressPostalCode: '#mailAddressPostal',
    editButton: '#schoolDetailsEditButton',
    editMailingAddressCountry: '#mailAddressCountry',
    editMailingAddressLine1: '#mailAddressLine1',
    editMailingAddressProvince: '#mailAddressProvince',
    editPopupConfirmButton: '#resolveBtn',
    editPopupReturnButton: '#rejectBtn',
    editSaveButton: '#saveButton',
    resolveBtn: '#resolveBtn',
    resolveButton:'#resolveBtn',
    saveButton: '#saveButton',
    schoolDetailsEmail: '#schoolDetailsEmail',
    schoolDetailsNlc: '#schoolDetailsNlc',
    schoolDetailsPhoneNumber: '#schoolDetailsPhoneNumber',
    schoolDetailsWebsite: 'form > div > div:nth-child(2) > div > div:nth-child(6) > div:nth-child(4) > div > div > div > div > div > div:nth-child(3) > input',
    schoolDisplayNameTitle: '#displayName',
    schoolGradesDropdown: '#schoolGrades',
    schoolGradesValue: '#schoolGradesValue',
    schoolMincodeTitle: '#schoolMincodeTitle',
    schoolNameNoSpecialChars: 'div.safe-name',
    subjectHeading: 'h2.subjectHeading'
  },
  schoolList: {
    schoolRow: '.hoverTable'
  },
  sdcSchoolStudentCollection: {
    sdcCollectionStepTwo: {
      removeRecord: '#removeRecord',
      removeRecordRejectButton: '#rejectBtn',
      removeRecordConfirmButton: '#resolveBtn',
    }
  },

  secureExchangeDetail: {
    addAttachmentConvButton: '#addAttachmentConvButton',
    addStudentConvButton: '#addStudentConvButton',
    editOptionsMenu: '#editOptionsMenu',
    newMessagePostBtn: '#newMessagePostBtn',
    newMessageToConvBtn: '#newMessageToConvBtn',
    newMessageToConvTextArea: '#newMessageToConvTextArea',
    timelineConfirmYesButton: '.v-btn',
    timelineContent: '.v-timeline-item__body',
    timelineRemoveButton: 'div.v-card-actions > button'
  },
  secureExchangeInbox: {
    addAttachmentButton: '#addAttachmentConvButton',
    filterSearchButton: '#searchButton',
    filterSubjectInput: '#subjectInput',
    filtersButton: '#filterid',
    newMessageButton: '#newMessageBtn',
    newMessageTextArea: '#newMessageTextArea',
    secureExchangeResults: '.v-data-table__tbody',
    uploadDocumentTypeCodeSelect: '#uploadDocumentTypeCodeSelect'
  },
  secureExchangeNewMessage: {
    addStudentToNewMessageBtn: '#addStudentID',
    attachFileID: '#attachFileID',
    newMessagePostBtn: '#newMessagePostBtn',
    newMessageTextArea: '#newMessageTextArea',
    subjectTxtField: '#subjectTxtField',
    toInputDropdown: '#schoolNameTxtField'
  },
  secureExchangeStudentUpload: { //common component
    addStudentID: '#addStudentToNewMessageBtn',
    searchPenBtn: '#searchPenBtn',
    studentPenTextField: '#studentPenTextField'
  },
  snackbar: {
    mainSnackBar: '#mainSnackBar'
  },
  specialEducationComponent: {
    tab: '#specialEdTab',
    summaryButton: '#specialEdSummaryButton',
    headcountCard: '.special-ed-headcount-card',
    headcountHeader: '.special-ed-headcount-header',
    headcountColumnData: '.special-ed-headcount-column-data',
    filterButton: '#filters',
  },
  activeFiltersDrawer: {
    drawer: '.v-navigation-drawer--active',
  },
  ellComponent: {
    tab: '#engLangTab',
    filterButton: '#filters',
    summaryButton: '#engLangSummaryButton',
    headcountCard: '.ell-headcount-card',
    headcountHeader: '.ell-headcount-header',
    headcountColumnData: '.ell-headcount-column-data'
  },
  studentLevelData: {
    detailsLoadingBar: 'div[class*=\'v-progress-linear--active\']',
    documentUploadButton: '#uploadButton',
    documentReUploadButton: '#uploadAgainButton',
    formHint: 'p.form-hint',
    legalLastNameValidationTextInput: '#legalLastNameValidationTextInput',
    stepOneNextButton: '#step-1-next-button-school',
    stepTwoNextButton: '#step-2-next-button-school',
    stepThreeNextButton: '#step-3-next-button-school',
    stepFourNextButton: '#step-4-next-button-school',
    stepFiveNextButton: '#step-5-next-button-school',
    postalCodeValidationTextInput: '#postalCodeValidationTextInput',
    removeRecord: '#removeRecord',
    saveRecordButton: '#saveRecord',
    stepFive:'#step-5',
    stepFour:'#step-4',
    stepOne:'#step-1',
    stepSix:'#step-6',
    stepThree:'#step-3',
    stepTwo:'#step-2',
    studentsFound: '#studentsFound',
    warningAndErrorSummary: '#warningAndErrorSummary',
    totalStudentsWithIssues: '#totalStudentsWithIssues',
    totalStudentsWithIssuesCount: '#totalStudentsWithIssuesCount',
    infoWarningCount: '#infoWarningCount',
    errorCount: '#errorCount',
    fundingWarningCount: '#fundingWarningCount',
    fixSelected: '#fixSelected',
    fixAll: '#fixAll',
    selectStudentCheckbox: 'td.v-data-table__td.v-data-table-column--no-padding.v-data-table-column--align-start > div',
    selectedStudentsPaginator: '.footer-text',
    backToDataIssues: 'div.v-col.v-col-6.mt-1.d-flex.justify-start > a',
    stepThreeSearchField: '#searchInput',
    stepThreeSearchBtn: '#search',
    stepThreeClearBtn: '#clear',
    stepThreeFirstRow: '.v-data-table__tbody > tr:first-child',
    stepThreeStudentsFound: '#studentsFound',
    stepTwoNameFilter: '#legalUsualNameSearch',
    stepTwoPenLocalIdFilter: '#penSearch',
    stepTwoSearchButton: '#searchButton',
    stepTwoTableFirstRow: 'div > div.v-table__wrapper > table > tbody > tr > td:nth-child(4)',
    stepTwoTableAllRows: 'div > div.v-table__wrapper > table > tbody > tr',
    stepTwoClearSearchFilter: '#clearSearch',
    duplicatePenFilter: '#duplicatePenFilter',
    editStudentClearfilter: '#clearFilters'
  },
  userActivationPage: {
    mincodeInput: '#instituteIdentifierTextField',
    primaryTextActivationCodeInput: '#primaryEdxCodeTextField',
    personalActivationCodeInput: '#personalActivationCodeTextField',
    userActivationSubmitButton: '#edxUserActivationSubmitBtn',
    userActivationSnackBar: '.v-snackbar__content',
    userActivationErrorMessageSnackBar: '#user_activation_error_message',
    acceptTermsCheckbox: '#acceptTOU'
  }
};
