# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Backend

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - 'feature/**'
      - 'Feature/**'
      - 'fix/*'
      - 'Fix/*'
    paths: 
      - 'backend/src/**'
      - 'backend/tests/unit/**'
  pull_request:
    branches: [ master ]
    paths: 
      - 'backend/src/**'
      - 'backend/tests/unit/**'

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run lint:fix
    - run: npm run test:unit
      env:
        NODE_ENV: 'test'
