# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Backend

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - 'feature/**'
      - 'Feature/**'
      - 'fix/*'
      - 'Fix/*'
    paths: 
      - 'backend/src/**'
      - 'backend/tests/unit/**'
  pull_request:
    branches: [ master ]
    paths: 
      - 'backend/src/**'
      - 'backend/tests/unit/**'

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run lint:fix
    - run: npm run test:unit
      env:
        NODE_ENV: 'test'

  sonarcloud:
    name: Build (Sonar Cloud)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Node install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.exclusions=**/tests/**,.github/**/*,*.md
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
            -Dsonar.project.monorepo.enabled=true
            -Dsonar.projectKey=bcgov_EDUC-EDX
            -Dsonar.sources=backend/src
            -Dsonar.tests=backend/tests
            -Dsonar.working.directory=backend
