# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'feature/**'
      - 'Feature/**'
      - 'fix/*'
      - 'Fix/*'
    paths: 
      - 'frontend/src/**'
  pull_request:
    branches: [ master ]
    paths: 
      - 'frontend/src/**'

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend
        
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run lint:fix

  sonarcloud:
    name: Build (Sonar Cloud)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        #with:
          #args: >
            #-Dsonar.exclusions=**/test/**,.github/**/*,*.md
            #-Dsonar.organization=bcgov-sonarcloud
            #-Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
            #-Dsonar.project.monorepo.enabled=true
            #-Dsonar.projectKey=${{ github.event.repository.name }}
            #-Dsonar.sources=frontend
            #-Dsonar.tests=frontend/tests
