name: Institute - Primary Code Onboarding

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:

defaults:
  run:
    working-directory: ./tools/onboarding
jobs:
  openshift-ci-cd:
    name: Send out initial onboarding primary codes for institutions
    # ubuntu-latest can also be used.
    runs-on: ubuntu-22.04
    environment: dev

    outputs:
      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Dump CSV data
      run: echo "${{ secrets.EDX_ONBOARDING_CSV }}" > user-records.csv

    - name: Dump environment data into .env file
      run: |
        cat << EOF > .env
        SOAM_CLIENT_ID="${{ secrets.SOAM_EDX_ONBOARDING_PRIMARY_CODE_CLIENT_ID }}"
        SOAM_CLIENT_SECRET="${{ secrets.SOAM_EDX_ONBOARDING_PRIMARY_CODE_CLIENT_SECRET }}"
        SOAM_TOKEN_URL="${{ secrets.SOAM_TOKEN_URL }}"
        INSTITUTE_SERVICE_URL="${{ secrets.INSTITUTE_API_URL }}"
        EDX_API_BASE_URL="${{ secrets.EDX_API_BASE_URL }}"
        CHES_CLIENT_ID="${{ secrets.CHES_CLIENT_ID }}"
        CHES_CLIENT_SECRET="${{ secrets.CHES_CLIENT_SECRET }}"
        CHES_TOKEN_URL="${{ secrets.CHES_TOKEN_URL }}"
        CHES_EMAIL_URL="${{ secrets.CHES_EMAIL_URL }}"
        ONBOARDING_INSTITUTE_TYPE="${{ vars.ONBOARDING_INSTITUTE_TYPE }}"
        EOF

    - name: Install dependencies, build & execute onboarding tool
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies and build the tool
      run: npm install && npm run build

    - name: Send onboarding messages to new institute users
      run: npm start
