name: Daily Regression
on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-5'

jobs:
  Regression:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: test-e2e
    steps:
      - uses: actions/checkout@v1
      - name: cypress.env.json
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
      - uses: actions/checkout@v3
        name: Checkout
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
#      - name: Upload Failure Screenshot
#        uses: actions/upload-artifact@v3
#        if: ${{ failure() }}
#        with:
#          name: Screenshot
#          path: /home/runner/work/EDUC-EDX/EDUC-EDX/test/src/screenshots
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "EDX Daily Regression - DEV --->"
          icon_emoji: ":bell:"
          channel: "educ-automation-failures"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK_FAILURES }}
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: success()
        with:
          type: ${{ job.status }}
          job_name: "EDX Daily Regression - DEV --->"
          icon_emoji: ":bell:"
          channel: "pen-automation-notifications"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}




