name: Daily Regression
on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-5'

jobs:
  Regression:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: test
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - run: npm install
      - run: npm run regression
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          EDX_API_BASE_URL: ${{ secrets.EDX_API_BASE_URL }}
          API_HTML_STATUS_CLASS_THRESHOLD: 399
          TOKEN_CLIENT_ID: ${{ secrets.AT_TOKEN_CLIENT_ID }}
          TOKEN_CLIENT_SECRET: ${{ secrets.AT_TOKEN_CLIENT_SECRET }}
          TOKEN_ENDPOINT: ${{ secrets.SOAM_TOKEN_URL }}
          TEST_ADMIN_USERNAME: ${{ secrets.AT_EDX_ADMIN_USERNAME }}
          TEST_ADMIN_PASSWORD: ${{ secrets.AT_EDX_ADMIN_PASSWORD }}
          TEST_ADMIN_DIGITAL_ID: ${{ secrets.AT_EDX_ADMIN_DIGITAL_ID }}
          TEST_EDX_ACTIVATE_USER_USERNAME: ${{ secrets.AT_EDX_ACTIVATE_USER_USERNAME }}
          TEST_EDX_ACTIVATE_USER_PWD: ${{ secrets.AT_EDX_ACTIVATE_USER_PWD }}
          PEN_LIST: ${{secrets.AT_PEN_LIST}}
          MINISTRY_OWNERSHIP_TEAM_ID: ${{secrets.AT_MINISTRY_OWNERSHIP_TEAM_ID}}
          CONTACT_IDENTIFIER: ${{secrets.AT_CONTACT_IDENTIFIER}}
          INSTITUTE_API_URL: ${{ secrets.INSTITUTE_API_URL}}
      - name: Upload Failure Screenshot
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: Screenshot
          path: /home/runner/work/EDUC-EDX/EDUC-EDX/test/src/screenshots/
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: failure()
        with:
          type: ${{ job.status }}
          job_name: "EDX Daily Regression - DEV --->"
          icon_emoji: ":bell:"
          channel: "educ-automation-failures"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK_FAILURES }}
      - name: Rocket.Chat Notification
        uses: RocketChat/Rocket.Chat.GitHub.Action.Notification@1.1.1
        if: success()
        with:
          type: ${{ job.status }}
          job_name: "EDX Daily Regression - DEV --->"
          icon_emoji: ":bell:"
          channel: "pen-automation-notifications"
          url: ${{ secrets.ROCKETCHAT_WEBHOOK }}




