name: Runner Test - TEST
on:
  workflow_dispatch:

env: 
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  RUNNER_DEPLOYMENT_NAMESPACE: ${{ secrets.RUNNER_DEPLOYMENT_NAMESPACE }}
  GITHUB_REPO: ${{ github.event.repository.name }}
  ORGANIZATION: bcgov
  GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  # deploy a self-hosted runner on OS
  DeployRunner:
    runs-on: ubuntu-latest
    outputs:
      runner_name: ${{ steps.deploy_runner.outputs.runner_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4
      - uses: ./.github/actions/deploy-os-runner
        id: deploy_runner
        with:
          runner-deployment-namespace: ${{ env.RUNNER_DEPLOYMENT_NAMESPACE }}
          openshift-token: ${{ env.OPENSHIFT_TOKEN }}
          openshift-server: ${{ env.OPENSHIFT_SERVER }}
          github-repo: ${{ env.GITHUB_REPO }}
          gh-access-token: ${{ env.GITHUB_ACCESS_TOKEN }}
          secret-ref: test-runner-test-secrets

  # run test on the runner
  SmokeTest:
    runs-on: ${{ needs.DeployRunner.outputs.runner_name }}
    environment: dev
    needs: [DeployRunner]
    defaults:
      run:
        working-directory: test
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - run: npm install
      - run: npm run runner-test
        if: ${{ always() }}


  # now burn it all down!!
  TearDown:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [DeployRunner, SmokeTest]
    steps:
      - uses: actions/checkout@v3
      - uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4
      - uses: ./.github/actions/teardown-os-runner
        with:
          runner-deployment-namespace: ${{ env.RUNNER_DEPLOYMENT_NAMESPACE }}
          runner-deployment-name: ${{ needs.DeployRunner.outputs.runner_name }}
          openshift-token: ${{ env.OPENSHIFT_TOKEN }}
          openshift-server: ${{ env.OPENSHIFT_SERVER }}


